apiVersion: apps/v1
kind: Deployment
metadata:
  name: team-d-app
  namespace: team-d
spec:
  replicas: 2
  selector:
    matchLabels:
      app: team-d-app
  template:
    metadata:
      labels:
        app: team-d-app
    spec:
      containers:
      - name: hello-kubernetes
        image: liorkamrat/hello-arc:latest
        ports:
        - containerPort: 8080
        env:
        - name: MESSAGE
          value: This is Team D Application deployed via Azure Arc in to a namespace!
---
apiVersion: v1
kind: Service
metadata:
  name: team-d-app
  namespace: team-d
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: team-d-app